CREATE TABLE B_ROOM
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMBER              INT          NOT NULL,
    HOTEL_FLOOR         INT          NOT NULL,
    PRICE               DOUBLE       NOT NULL,
    TOTAL_PRICE         DOUBLE,
    ROOM_CAPACITY       INT          NOT NULL,
    TYPE                VARCHAR(255) NOT NULL,
    STATUS              VARCHAR(255) NOT NULL,
    DESCRIPTION         VARCHAR(100) NOT NULL,
    CURRENT_GUEST_COUNT INT,
    TIME_FOR_PAY        TIMESTAMP,
    BOOKED_FROM         TIMESTAMP,
    BOOKED_TO           TIMESTAMP,
    CONSTRAINT UNIQUE_ROOM UNIQUE (NUMBER, HOTEL_FLOOR)
);


CREATE TABLE IF NOT EXISTS B_USER
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME  VARCHAR(255) NOT NULL UNIQUE,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME  VARCHAR(255) NOT NULL,
    EMAIL     VARCHAR(255) NOT NULL UNIQUE,
    PHONE     VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD  VARCHAR(255) NOT NULL,
    ROLE      VARCHAR(50)  NOT NULL,
    ROOM_ID   BIGINT,
    FOREIGN KEY (ROOM_ID) REFERENCES B_ROOM (ID) ON DELETE SET NULL
);
